use super::*;
use allow_core::{AllowConfig, FindingKind};
use std::fs;
use std::path::{Path, PathBuf};
use support::*;

mod finding_posture;
mod policy_entry;
mod policy_evidence;
mod policy_git;
mod policy_header;
mod policy_lifecycle;
mod policy_metadata;
mod policy_requirements;
mod policy_scope;
mod policy_selector;
mod policy_strings;
mod policy_workspace;
mod proptest_diff;
mod revision_companions;
mod revision_findings;
mod revision_git_parser;
mod structural_identity_posture;
mod support;
