//! Drift guard binding the checked-in matrix projection to the typed source
//! (#3905 PR D).
//!
//! `docs/assets/feature-configuration-matrix-v1.json` is the byte-exact
//! `serde_json::to_string_pretty` projection of
//! [`allow_report::supported_feature_configuration_matrix`]. It is the
//! single JSON surface that non-Rust CI consumers (the #3905 routing script
//! and workflows) read for configuration row IDs. This guard fails when the
//! checked-in projection drifts from the fresh matrix, and when it stops
//! parsing back into the typed contract, so the workflow-facing projection
//! can never silently diverge from the Rust source of truth. The matrix in
//! `allow-report` stays the only place rows are declared.
//!
//! The file is regenerated by rendering the fresh matrix with
//! [`allow_report::render_supported_feature_configuration_matrix_v1`] and
//! replacing the file contents verbatim (no trailing newline).

use allow_report::render_supported_feature_configuration_matrix_v1;
use allow_report::supported_feature_configuration_matrix;
use std::path::PathBuf;

/// Repo-relative location of the checked-in projection, named verbatim in
/// drift diagnostics so regeneration instructions stay concrete.
const PROJECTION_RELATIVE_PATH: &str = "docs/assets/feature-configuration-matrix-v1.json";

fn projection_path() -> Result<PathBuf, String> {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest_dir
        .parent()
        .and_then(|crates| crates.parent())
        .map(|root| root.join(PROJECTION_RELATIVE_PATH))
        .ok_or_else(|| "no repo root above the allow-report manifest dir".to_string())
}

fn read_checked_in_projection() -> Result<String, String> {
    let path = projection_path()?;
    std::fs::read_to_string(&path).map_err(|error| format!("read {}: {error}", path.display()))
}

fn render_fresh_matrix() -> Result<String, String> {
    render_supported_feature_configuration_matrix_v1(&supported_feature_configuration_matrix())
        .map_err(|error| format!("render fresh matrix: {error}"))
}

/// Byte-equality law: the checked-in projection must stay the deterministic
/// pretty-render of the fresh matrix. Trimmed comparison keeps the guard
/// insensitive to checkout line-ending normalization only; any content drift
/// fails with regeneration instructions naming the file.
#[test]
fn checked_in_projection_matches_the_fresh_matrix_render() -> Result<(), String> {
    let checked_in = read_checked_in_projection()?;
    let fresh = render_fresh_matrix()?;
    if checked_in.trim() != fresh.trim() {
        return Err(format!(
            "drift: {PROJECTION_RELATIVE_PATH} no longer equals \
             serde_json::to_string_pretty of \
             allow_report::supported_feature_configuration_matrix(); regenerate it by \
             rendering the fresh matrix and replacing the file contents verbatim"
        ));
    }
    Ok(())
}

/// Typed round-trip law: the projection must parse back into the typed
/// matrix contract and equal the fresh matrix, so JSON-only consumers read
/// exactly the rows the Rust contract declares. The matrix struct itself is
/// not nameable from outside the crate, so the deserialization target is
/// bound through a generic helper against the fresh matrix's concrete type
/// (`SupportedFeatureConfigurationMatrixV1`, deny_unknown_fields and all) —
/// never an untyped JSON tree.
#[test]
fn checked_in_projection_parses_back_into_the_typed_matrix() -> Result<(), String> {
    let checked_in = read_checked_in_projection()?;
    let fresh = supported_feature_configuration_matrix();
    if fresh.rows.is_empty() {
        return Err("drift guard: the fresh matrix unexpectedly carries no rows".to_string());
    }
    if parse_and_compare(&checked_in, &fresh)? {
        return Err(format!(
            "drift: {PROJECTION_RELATIVE_PATH} parses but disagrees with the fresh matrix"
        ));
    }
    Ok(())
}

/// Deserialize `checked_in` into the same concrete type as `fresh` and
/// report whether the two disagree.
fn parse_and_compare<T>(checked_in: &str, fresh: &T) -> Result<bool, String>
where
    T: serde::de::DeserializeOwned + PartialEq,
{
    let parsed: T = serde_json::from_str(checked_in).map_err(|error| {
        format!("{PROJECTION_RELATIVE_PATH} does not parse as the typed matrix: {error}")
    })?;
    Ok(parsed != *fresh)
}
