use std::collections::BTreeSet;

pub(crate) fn has_nearby_safety_comment(safety_comments: &BTreeSet<u32>, line_no: u32) -> bool {
    let first = line_no.saturating_sub(3).max(1);
    (first..=line_no).any(|line| safety_comments.contains(&line))
}

/// Returns true when `comment_text` is the raw text of a tree-sitter
/// `line_comment` or `block_comment` node whose body starts with `SAFETY:`.
pub(crate) fn comment_node_text_is_safety_marker(comment_text: &str, kind: &str) -> bool {
    match kind {
        "line_comment" => line_comment_body(comment_text).is_some_and(|body| {
            body.starts_with("SAFETY:")
        }),
        "block_comment" => block_comment_body(comment_text).is_some_and(|body| {
            body.starts_with("SAFETY:")
        }),
        _ => false,
    }
}

fn line_comment_body(text: &str) -> Option<&str> {
    let rest = text.strip_prefix("//")?;
    let rest = match rest.chars().next()? {
        '/' | '!' => rest.get(1..).unwrap_or(""),
        _ => rest,
    };
    Some(rest.trim_start())
}

fn block_comment_body(text: &str) -> Option<&str> {
    let mut rest = text.trim_start().strip_prefix("/*")?;
    rest = rest.strip_prefix('*').unwrap_or(rest);

    for line in rest.lines() {
        let line = line.trim_end().strip_suffix("*/").unwrap_or(line).trim_end();
        let content = line
            .trim_start()
            .strip_prefix('*')
            .unwrap_or(line)
            .trim_start();
        if !content.is_empty() {
            return Some(content);
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn has_nearby_safety_comment_call_presence_observer() {
        let safety_comments = BTreeSet::from([1, 4, 10]);

        assert!(has_nearby_safety_comment(&safety_comments, 1));
        assert!(has_nearby_safety_comment(&safety_comments, 3));
        assert!(has_nearby_safety_comment(&safety_comments, 7));
        assert!(!has_nearby_safety_comment(&safety_comments, 8));
        assert!(!has_nearby_safety_comment(&safety_comments, 0));
    }

    #[test]
    fn comment_node_text_is_safety_marker_line_comment_forms() {
        assert!(comment_node_text_is_safety_marker(
            "// SAFETY: checked by caller",
            "line_comment"
        ));
        assert!(comment_node_text_is_safety_marker(
            "/// SAFETY: doc comment form",
            "line_comment"
        ));
        assert!(comment_node_text_is_safety_marker(
            "//! SAFETY: inner doc form",
            "line_comment"
        ));

        assert!(!comment_node_text_is_safety_marker(
            "// safety: lowercase marker",
            "line_comment"
        ));
        assert!(!comment_node_text_is_safety_marker(
            "// see the SAFETY: section of the RFC",
            "line_comment"
        ));
        assert!(!comment_node_text_is_safety_marker(
            "// discussing SAFETY: trade-offs",
            "line_comment"
        ));
    }

    #[test]
    fn comment_node_text_is_safety_marker_block_comment_forms() {
        assert!(comment_node_text_is_safety_marker(
            "/* SAFETY: generated by bindgen */",
            "block_comment"
        ));
        assert!(comment_node_text_is_safety_marker(
            "/* SAFETY: first line\n * continued proof\n */",
            "block_comment"
        ));
        assert!(comment_node_text_is_safety_marker(
            "/** SAFETY: doc block form */",
            "block_comment"
        ));

        assert!(!comment_node_text_is_safety_marker(
            "/* note about SAFETY: not a proof */",
            "block_comment"
        ));
    }
}
