use std::collections::BTreeSet;

pub(crate) fn safety_comment_lines(source: &str) -> BTreeSet<u32> {
    source
        .lines()
        .enumerate()
        .filter_map(|(line_idx, line)| is_safety_comment(line).then_some((line_idx + 1) as u32))
        .collect()
}

pub(crate) fn has_nearby_safety_comment(safety_comments: &BTreeSet<u32>, line_no: u32) -> bool {
    let first = line_no.saturating_sub(3).max(1);
    (first..=line_no).any(|line| safety_comments.contains(&line))
}

fn is_safety_comment(line: &str) -> bool {
    let trimmed = line.trim_start();
    if trimmed.starts_with("//") || trimmed.starts_with("/*") || trimmed.starts_with('*') {
        return trimmed.contains("SAFETY:");
    }
    line.split_once("//")
        .is_some_and(|(_, comment)| comment.contains("SAFETY:"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn safety_comment_lines_call_presence_observer() {
        let source = r#"
fn main() {
    // SAFETY: caller validates the pointer.
    unsafe { load(ptr) };
    let text = "SAFETY: not a comment";
    /* SAFETY: block comment form */
    * SAFETY: block continuation form
    unsafe { store(ptr) }; // SAFETY: inline trailing form
}
"#;

        let lines = safety_comment_lines(source);

        assert!(lines.contains(&3));
        assert!(lines.contains(&6));
        assert!(lines.contains(&7));
        assert!(lines.contains(&8));
        assert!(!lines.contains(&5));
    }

    #[test]
    fn has_nearby_safety_comment_call_presence_observer() {
        let safety_comments = BTreeSet::from([1, 4, 10]);

        assert!(has_nearby_safety_comment(&safety_comments, 1));
        assert!(has_nearby_safety_comment(&safety_comments, 3));
        assert!(has_nearby_safety_comment(&safety_comments, 7));
        assert!(!has_nearby_safety_comment(&safety_comments, 8));
        assert!(!has_nearby_safety_comment(&safety_comments, 0));
    }

    #[test]
    fn is_safety_comment_call_presence_observer() {
        assert!(is_safety_comment("    // SAFETY: checked by caller"));
        assert!(is_safety_comment("/* SAFETY: generated by bindgen */"));
        assert!(is_safety_comment("    * SAFETY: continued proof"));
        assert!(is_safety_comment("unsafe { f() }; // SAFETY: inline proof"));

        assert!(!is_safety_comment("    // safety: lowercase marker"));
        assert!(!is_safety_comment("let text = \"SAFETY: not a comment\";"));
    }

    #[test]
    fn is_safety_comment_boundary_discriminator() {
        assert!(is_safety_comment("// SAFETY: line comment"));
        assert!(is_safety_comment("/* SAFETY: block comment"));
        assert!(is_safety_comment("* SAFETY: block continuation"));
        assert!(is_safety_comment(
            "let _ = f(); // SAFETY: trailing comment"
        ));

        assert!(!is_safety_comment("SAFETY: bare text is not a comment"));
        assert!(!is_safety_comment(
            "# SAFETY: shell-style marker is not a Rust comment"
        ));
        assert!(!is_safety_comment(
            "let _ = f(); /* proof without marker */"
        ));
    }
}
