use std::collections::BTreeSet;

pub(crate) fn safety_comment_lines(source: &str) -> BTreeSet<u32> {
    source
        .lines()
        .enumerate()
        .filter_map(|(line_idx, line)| is_safety_comment(line).then_some((line_idx + 1) as u32))
        .collect()
}

pub(crate) fn has_nearby_safety_comment(safety_comments: &BTreeSet<u32>, line_no: u32) -> bool {
    let first = line_no.saturating_sub(3).max(1);
    (first..=line_no).any(|line| safety_comments.contains(&line))
}

fn is_safety_comment(line: &str) -> bool {
    let trimmed = line.trim_start();
    if trimmed.starts_with("//") {
        // The comment body (after // and optional whitespace) must START
        // with "SAFETY:", not merely contain it — prevents false positives
        // like "// see the SAFETY: section of the RFC" (#1797).
        return comment_body_starts_with_safety(trimmed, "//");
    }
    if trimmed.starts_with("/*") {
        return comment_body_starts_with_safety(trimmed, "/*");
    }
    if trimmed.starts_with('*') {
        return comment_body_starts_with_safety(trimmed, "*");
    }
    // For inline trailing comments (code before //), extract the comment
    // portion. Use rsplit_once to find the LAST // on the line, which handles
    // strings containing // better than split_once (#1797).
    line.rsplit_once("//")
        .is_some_and(|(_, comment)| comment.trim_start().starts_with("SAFETY:"))
}

/// Check that a comment (starting with the given prefix) has a body that
/// begins with "SAFETY:" after the prefix and optional whitespace.
fn comment_body_starts_with_safety(comment: &str, prefix: &str) -> bool {
    comment
        .strip_prefix(prefix)
        .map(|body| body.trim_start().starts_with("SAFETY:"))
        .unwrap_or(false)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn safety_comment_lines_call_presence_observer() {
        let source = r#"
fn main() {
    // SAFETY: caller validates the pointer.
    unsafe { load(ptr) };
    let text = "SAFETY: not a comment";
    /* SAFETY: block comment form */
    * SAFETY: block continuation form
    unsafe { store(ptr) }; // SAFETY: inline trailing form
}
"#;

        let lines = safety_comment_lines(source);

        assert!(lines.contains(&3));
        assert!(lines.contains(&6));
        assert!(lines.contains(&7));
        assert!(lines.contains(&8));
        assert!(!lines.contains(&5));
    }

    #[test]
    fn has_nearby_safety_comment_call_presence_observer() {
        let safety_comments = BTreeSet::from([1, 4, 10]);

        assert!(has_nearby_safety_comment(&safety_comments, 1));
        assert!(has_nearby_safety_comment(&safety_comments, 3));
        assert!(has_nearby_safety_comment(&safety_comments, 7));
        assert!(!has_nearby_safety_comment(&safety_comments, 8));
        assert!(!has_nearby_safety_comment(&safety_comments, 0));
    }

    #[test]
    fn is_safety_comment_call_presence_observer() {
        assert!(is_safety_comment("    // SAFETY: checked by caller"));
        assert!(is_safety_comment("/* SAFETY: generated by bindgen */"));
        assert!(is_safety_comment("    * SAFETY: continued proof"));
        assert!(is_safety_comment("unsafe { f() }; // SAFETY: inline proof"));

        assert!(!is_safety_comment("    // safety: lowercase marker"));
        assert!(!is_safety_comment("let text = \"SAFETY: not a comment\";"));
    }

    #[test]
    fn is_safety_comment_boundary_discriminator() {
        assert!(is_safety_comment("// SAFETY: line comment"));
        assert!(is_safety_comment("/* SAFETY: block comment"));
        assert!(is_safety_comment("* SAFETY: block continuation"));
        assert!(is_safety_comment(
            "let _ = f(); // SAFETY: trailing comment"
        ));

        assert!(!is_safety_comment("SAFETY: bare text is not a comment"));
        assert!(!is_safety_comment(
            "# SAFETY: shell-style marker is not a Rust comment"
        ));
        assert!(!is_safety_comment(
            "let _ = f(); /* proof without marker */"
        ));
    }

    #[test]
    fn is_safety_comment_rejects_substring_false_positives() {
        // Regression for #1797: "SAFETY:" as a substring anywhere in a
        // comment is NOT a safety comment — the marker must be at the start
        // of the comment body.
        assert!(!is_safety_comment("// see the SAFETY: section of the RFC"));
        assert!(!is_safety_comment("// discussing SAFETY: trade-offs"));
        assert!(!is_safety_comment("/* note about SAFETY: not a proof */"));
        // Note: string literals containing "// SAFETY:" still produce false
        // positives without tree-sitter comment-node awareness. That's a
        // separate follow-up tracked in the issue.
    }
}
