use super::*;

#[test]
fn propose_json_renderer_records_options_summary_and_defaults() {
    let report = ProposeReport {
        inventory: InventoryContext::source_syntax(
            "git_tracked",
            Some("H:/Code/Rust/cargo-allow"),
            Some(76),
        ),
        kind: Some("panic"),
        expires: "2026-08-02",
        policy_output: Some("target/cargo-allow/proposed.toml"),
        force: true,
        findings_scanned: 54,
        baseline_debt_entries_proposed: 2,
        unsafe_baseline_debt_entries_proposed: 1,
        truncated_new_findings: 0,
        unreceiptable_new_findings: 0,
        unreceiptable_reason: None,
        mutation_receipt: sample_mutation_receipt(),
    };
    let json = render_propose_json(report.clone());
    let styled = render_propose_human_styled(report.clone(), Style::ANSI);

    assert!(json.contains("\"schema_id\": \"cargo-allow.propose.v1\""));
    assert!(json.contains("\"command\": \"propose\""));
    assert!(json.contains("\"source\": \"git_tracked\""));
    assert!(json.contains("\"files_scanned\": 76"));
    assert!(json.contains("\"kind\": \"panic\""));
    assert!(json.contains("\"expires\": \"2026-08-02\""));
    assert!(json.contains("\"policy_output\": \"target/cargo-allow/proposed.toml\""));
    assert!(json.contains("\"force\": true"));
    assert!(json.contains("\"findings_scanned\": 54"));
    assert!(json.contains("\"baseline_debt_entries_proposed\": 2"));
    assert!(json.contains("\"unsafe_baseline_debt_entries_proposed\": 1"));
    assert!(json.contains("\"follow_up_queues\""));
    assert!(json.contains("\"signal\": \"baseline_debt_entries_proposed\""));
    assert!(json.contains("\"label\": \"baseline debt entries\""));
    assert!(json.contains("\"route_kind\": \"worklist_filter\""));
    assert!(json.contains("\"item_kind\": \"baseline_debt\""));
    assert!(json.contains("\"worklist_filter\": \"baseline_debt\""));
    assert!(json.contains("\"command\": \"cargo-allow worklist --baseline-debt --format json\""));
    assert!(json.contains("\"signal\": \"unsafe_baseline_debt_entries_proposed\""));
    assert!(json.contains("\"label\": \"unsafe baseline debt entries\""));
    assert!(json.contains("\"route_kind\": \"worklist_item_kind\""));
    assert!(json.contains("\"item_kind\": \"weak_evidence_reference\""));
    assert!(json.contains(
        "\"command\": \"cargo-allow worklist --item-kind weak_evidence_reference --kind unsafe --format json\""
    ));
    assert!(json.contains("\"owner\": \"unowned\""));
    assert!(json.contains("\"classification\": \"baseline_debt\""));
    assert!(styled.contains("classification: \u{1b}[31mbaseline_debt\u{1b}[0m"));
    assert!(
        !styled.contains("target/cargo-allow/proposed.toml\u{1b}"),
        "repository-controlled output paths must stay unstyled"
    );
    let _expected = format!(
        r#"{{
  "schema_version": 1,
  "schema_id": "cargo-allow.propose.v1",
  "tool": "cargo-allow",
  "command": "propose",
  "claim_boundary": {},
  "scanner_limitations": {},
  "inventory": {{
    "scope": "source_tree",
    "scanner": "source_syntax",
    "source": "git_tracked",
    "root": "H:/Code/Rust/cargo-allow",
    "files_scanned": 76
  }},
  "options": {{
    "kind": "panic",
    "expires": "2026-08-02",
    "policy_output": "target/cargo-allow/proposed.toml",
    "force": true
  }},
  "summary": {{
    "findings_scanned": 54,
    "baseline_debt_entries_proposed": 2,
    "unsafe_baseline_debt_entries_proposed": 1,
    "truncated_new_findings": 0,
    "unreceiptable_new_findings": 0,
    "unreceiptable_reason": null
  }},
  "follow_up_queues": [
    {{
      "signal": "baseline_debt_entries_proposed",
      "label": "baseline debt entries",
      "route_kind": "worklist_filter",
      "item_kind": "baseline_debt",
      "worklist_filter": "baseline_debt",
      "count": 2,
      "command": "cargo-allow worklist --baseline-debt --format json"
    }},
    {{
      "signal": "unsafe_baseline_debt_entries_proposed",
      "label": "unsafe baseline debt entries",
      "route_kind": "worklist_item_kind",
      "item_kind": "weak_evidence_reference",
      "count": 1,
      "command": "cargo-allow worklist --item-kind weak_evidence_reference --kind unsafe --format json"
    }}
  ],
  "generated_entry_defaults": {{
    "owner": "unowned",
    "classification": "baseline_debt",
    "reason": "Generated by cargo-allow propose; requires human review.",
    "expires": "2026-08-02"
  }}
}}
"#,
        render_claim_boundary_json(),
        render_scanner_limitations_json()
    );
    let parsed = serde_json::from_str::<serde_json::Value>(&json);
    assert!(parsed.is_ok(), "propose output must remain valid JSON");
    let Some(parsed) = parsed.ok() else {
        return;
    };
    assert_eq!(
        parsed
            .pointer("/mutation_receipt/operation")
            .and_then(serde_json::Value::as_str),
        Some("propose")
    );
    assert_eq!(
        parsed
            .pointer("/mutation_receipt/changed_allow_ids")
            .and_then(serde_json::Value::as_array)
            .map(Vec::len),
        Some(3)
    );

    let text = render_propose_human(report);

    assert!(text.contains("cargo-allow propose summary"));
    assert!(
        text.contains("inventory: source_tree/source_syntax via git_tracked; files scanned: 76")
    );
    assert!(text.contains("source_tree_root: H:/Code/Rust/cargo-allow"));
    assert!(text.contains("kind filter: panic"));
    assert!(text.contains("findings scanned: 54"));
    assert!(text.contains("baseline_debt entries proposed: 2"));
    assert!(text.contains("unsafe baseline_debt entries proposed: 1"));
    assert!(text.contains("owner: unowned"));
    assert!(text.contains("classification: baseline_debt"));
    assert!(text.contains("expires: 2026-08-02"));
    assert!(text.contains("output: target/cargo-allow/proposed.toml"));
    assert!(text.contains("follow_up_queues:"));
    assert!(text.contains("cargo-allow worklist --baseline-debt --format json"));
    assert!(text.contains(
        "cargo-allow worklist --item-kind weak_evidence_reference --kind unsafe --format json"
    ));
    assert!(text.contains("generated debt still requires human review"));
    assert!(text.contains("Claim boundary: scanned source-tree/source syntax only"));
}

#[test]
fn propose_renderer_omits_follow_up_queues_when_nothing_proposed() {
    let mut report = ProposeReport {
        inventory: InventoryContext::source_syntax("git_tracked", None, Some(12)),
        kind: None,
        expires: "2026-08-02",
        policy_output: None,
        force: false,
        findings_scanned: 12,
        baseline_debt_entries_proposed: 0,
        unsafe_baseline_debt_entries_proposed: 0,
        truncated_new_findings: 0,
        unreceiptable_new_findings: 0,
        unreceiptable_reason: None,
        mutation_receipt: sample_mutation_receipt(),
    };
    report.mutation_receipt.result = "stdout";
    report.mutation_receipt.changed_allow_ids.clear();
    report.mutation_receipt.before_fingerprints.clear();
    report.mutation_receipt.after_fingerprints.clear();

    let json = render_propose_json(report.clone());
    let text = render_propose_human(report);

    assert!(!json.contains("\"follow_up_queues\""));
    assert!(json.contains("\"mutation_receipt\""));
    assert!(json.contains("\"result\": \"stdout\""));
    assert!(json.contains("\"changed_allow_ids\": []"));
    assert!(json.contains("\"after_fingerprints\": []"));
    assert!(!text.contains("follow_up_queues:"));
}

fn sample_mutation_receipt() -> MutationReceipt<'static> {
    MutationReceipt {
        operation: "propose",
        tool_version: "0.1.10",
        repo_root: Some("H:/Code/Rust/cargo-allow"),
        config_source: Some("policy/allow.toml"),
        ledger_ids: Vec::new(),
        changed_allow_ids: vec!["allow-0001", "allow-0002", "allow-0003"],
        before_fingerprints: vec![None, None, None],
        after_fingerprints: vec![
            Some(
                "sha256:v1:0000000000000000000000000000000000000000000000000000000000000001"
                    .to_string(),
            ),
            Some(
                "sha256:v1:0000000000000000000000000000000000000000000000000000000000000002"
                    .to_string(),
            ),
            Some(
                "sha256:v1:0000000000000000000000000000000000000000000000000000000000000003"
                    .to_string(),
            ),
        ],
        result: "written",
        next_commands: vec![
            "cargo-allow worklist --baseline-debt --format json".to_string(),
            "cargo-allow check --mode no-new".to_string(),
        ],
    }
}
