use crate::{
    add, adoption, diff, doctor, explain, list, migrate, propose, prune, refresh, spec_system, why,
    worklist,
};

pub(crate) struct ArtifactSample {
    pub(crate) name: &'static str,
    pub(crate) schema_name: &'static str,
    pub(crate) json: String,
    pub(crate) expected_command: &'static str,
    pub(crate) expected_top_level_keys: &'static [&'static str],
}

pub(crate) fn command_artifact_samples() -> Vec<ArtifactSample> {
    vec![
        ArtifactSample {
            name: "add",
            schema_name: "add",
            json: add::sample_add_json_for_contract_test(),
            expected_command: "add",
            expected_top_level_keys: &[
                "allow_entry",
                "claim_boundary",
                "command",
                "inventory",
                "mutation_receipt",
                "options",
                "scanner_limitations",
                "schema_id",
                "schema_version",
                "selected_finding",
                "summary",
                "tool",
            ],
        },
        ArtifactSample {
            name: "doctor",
            schema_name: "doctor",
            json: doctor::sample_doctor_json_for_contract_test(),
            expected_command: "doctor",
            expected_top_level_keys: &[
                "claim_boundary",
                "command",
                "config",
                "evidence_repair_queues",
                "federation",
                "file_families",
                "inventory",
                "root",
                "scanner_limitations",
                "schema_id",
                "schema_version",
                "tool",
            ],
        },
        ArtifactSample {
            name: "core-adoption-plan",
            schema_name: "core-adoption-plan",
            json: adoption::sample_adoption_json_for_contract_test(),
            expected_command: "adopt",
            expected_top_level_keys: &[
                "claim_boundary",
                "command",
                "inventory",
                "plan",
                "scanner_limitations",
                "schema_id",
                "schema_version",
                "tool",
            ],
        },
        ArtifactSample {
            name: "explain",
            schema_name: "explain",
            json: explain::sample_explain_json_for_contract_test(),
            expected_command: "explain",
            expected_top_level_keys: &[
                "allow_entry",
                "claim_boundary",
                "command",
                "current_findings",
                "evidence_references",
                "inventory",
                "match_outcomes",
                "next",
                "scanner_limitations",
                "schema_id",
                "schema_version",
                "summary",
                "tool",
            ],
        },
        ArtifactSample {
            name: "why",
            schema_name: "why",
            json: why::sample_why_json_for_contract_test(),
            expected_command: "why",
            expected_top_level_keys: &[
                "candidate_entries",
                "claim_boundary",
                "command",
                "evaluation",
                "finding",
                "inventory",
                "next",
                "outcome",
                "scanner_limitations",
                "schema_id",
                "schema_version",
                "tool",
            ],
        },
        ArtifactSample {
            name: "add-finding-plan",
            schema_name: "add-finding-plan",
            json: why::sample_add_finding_plan_json_for_contract_test(),
            expected_command: "why",
            expected_top_level_keys: &[
                "candidates",
                "claim_boundary",
                "command",
                "evaluation",
                "finding",
                "inventory",
                "inventory_basis_identity",
                "outcome",
                "policy",
                "proof_plans",
                "repository",
                "required_fields",
                "scanner_limitations",
                "schema_id",
                "schema_version",
                "tool",
                "tool_version",
            ],
        },
        ArtifactSample {
            name: "add-plan-application",
            schema_name: "add-plan-application",
            json: add::sample_add_plan_application_json_for_contract_test(),
            expected_command: "add",
            expected_top_level_keys: &[
                "added_allow_id",
                "claim_boundary",
                "command",
                "finding_digest",
                "full_check_argv",
                "inventory",
                "plan_digest",
                "policy_after_digest",
                "policy_before_digest",
                "repository_identity",
                "scanner_limitations",
                "schema_id",
                "schema_version",
                "target_ledger",
                "targeted_recheck",
                "tool",
                "tool_version",
            ],
        },
        ArtifactSample {
            name: "list",
            schema_name: "list",
            json: list::sample_list_json_for_contract_test(),
            expected_command: "list",
            expected_top_level_keys: &[
                "allow_entries",
                "claim_boundary",
                "command",
                "filters",
                "inventory",
                "scanner_limitations",
                "schema_id",
                "schema_version",
                "summary",
                "tool",
            ],
        },
        ArtifactSample {
            name: "migrate",
            schema_name: "migrate",
            json: migrate::sample_migrate_json_for_contract_test(),
            expected_command: "migrate",
            expected_top_level_keys: &[
                "claim_boundary",
                "closeout",
                "command",
                "evidence_repair_queues",
                "input",
                "inventory",
                "mutation_receipt",
                "notes",
                "output",
                "scanner_limitations",
                "schema_id",
                "schema_version",
                "summary",
                "tool",
            ],
        },
        ArtifactSample {
            name: "propose",
            schema_name: "propose",
            json: propose::sample_propose_json_for_contract_test(),
            expected_command: "propose",
            expected_top_level_keys: &[
                "claim_boundary",
                "command",
                "follow_up_queues",
                "generated_entry_defaults",
                "inventory",
                "mutation_receipt",
                "options",
                "scanner_limitations",
                "schema_id",
                "schema_version",
                "summary",
                "tool",
            ],
        },
        ArtifactSample {
            name: "prune",
            schema_name: "prune",
            json: prune::sample_prune_json_for_contract_test(),
            expected_command: "prune",
            expected_top_level_keys: &[
                "claim_boundary",
                "command",
                "inventory",
                "mode",
                "mutation_receipt",
                "removed_toml_blocks",
                "scanner_limitations",
                "schema_id",
                "schema_version",
                "stale_entries",
                "summary",
                "tool",
            ],
        },
        ArtifactSample {
            name: "refresh",
            schema_name: "refresh",
            json: refresh::sample_refresh_json_for_contract_test(),
            expected_command: "refresh",
            expected_top_level_keys: &[
                "claim_boundary",
                "command",
                "inventory",
                "matched_finding",
                "mode",
                "mutation_receipt",
                "previous_last_seen",
                "refreshed_last_seen",
                "scanner_limitations",
                "schema_id",
                "schema_version",
                "summary",
                "tool",
            ],
        },
        ArtifactSample {
            name: "worklist",
            schema_name: "worklist",
            json: worklist::sample_worklist_json_for_contract_test(),
            expected_command: "worklist",
            expected_top_level_keys: &[
                "claim_boundary",
                "command",
                "filters",
                "inventory",
                "scanner_limitations",
                "schema_id",
                "schema_version",
                "summary",
                "tool",
                "work_items",
            ],
        },
        ArtifactSample {
            name: "spec_system",
            schema_name: "spec-system",
            json: spec_system::sample_spec_system_json_for_contract_test(),
            expected_command: "check",
            expected_top_level_keys: &[
                "artifacts",
                "claim_boundary",
                "command",
                "config_source",
                "config_provenance",
                "failed",
                "findings",
                "inventory",
                "links",
                "mode",
                "profile",
                "scanner_limitations",
                "schema_id",
                "schema_version",
                "source_tree_root",
                "status",
                "summary",
                "tool",
                "work_items",
            ],
        },
    ]
}

pub(crate) fn core_artifact_samples() -> Vec<ArtifactSample> {
    let audit_report_json = allow_report::render_json_with_context(
        "audit",
        &[],
        &[],
        false,
        allow_report::ReportContext::source_syntax(
            "filesystem_fallback",
            Some("fixtures/source-snapshot"),
            Some(7),
            None,
        ),
    );
    let check_report_json = allow_report::render_json_with_context(
        "check",
        &[],
        &[],
        false,
        allow_report::ReportContext::source_syntax(
            "git_tracked",
            Some("H:/Code/Rust/cargo-allow"),
            Some(42),
            None,
        ),
    );
    let mut receipt_context = allow_report::ReportContext::source_syntax(
        "git_tracked",
        Some("H:/Code/Rust/cargo-allow"),
        Some(42),
        None,
    );
    receipt_context.mode = Some("no-new");
    receipt_context.enforcement = Some(allow_report::RECEIPT_ENFORCEMENT_ENFORCING);
    receipt_context.policy_config = Some("policy/allow.toml");
    receipt_context.tool_version = Some(env!("CARGO_PKG_VERSION"));
    let receipt_json =
        allow_report::render_receipt_with_context("check", &[], false, receipt_context);
    let failed_receipt_json = allow_report::render_receipt_with_context(
        "check",
        &[],
        true,
        allow_report::ReportContext::source_syntax(
            "git_tracked",
            Some("H:/Code/Rust/cargo-allow"),
            Some(42),
            None,
        ),
    );
    let error_receipt_json = allow_report::render_error_receipt(
        "invalid policy field: \"mode\"",
        allow_report::ReportContext::source_syntax(
            "filesystem_fallback",
            Some("fixtures/source-snapshot"),
            Some(7),
            None,
        ),
    );
    let diff_base_json = allow_report::render_json_with_context(
        "diff",
        &[],
        &[],
        false,
        allow_report::ReportContext::source_syntax(
            "git_tracked",
            Some("H:/Code/Rust/cargo-allow"),
            Some(8),
            None,
        ),
    );
    let cfg = allow_core::AllowConfig::empty();
    let ledger = diff::DiffLedgerContext::new(&cfg, &cfg, &[], &[]);
    let diff_json = diff::render_diff_json_with_posture(diff_base_json, 0, &[], &ledger);
    vec![
        ArtifactSample {
            name: "audit_report",
            schema_name: "report",
            json: audit_report_json,
            expected_command: "audit",
            expected_top_level_keys: &[
                "claim_boundary",
                "command",
                "evidence_repair_queues",
                "failed",
                "findings",
                "inventory",
                "outcomes",
                "scanner_limitations",
                "schema_id",
                "schema_version",
                "status",
                "summary",
                "tool",
                "trend",
            ],
        },
        ArtifactSample {
            name: "check_report",
            schema_name: "report",
            json: check_report_json,
            expected_command: "check",
            expected_top_level_keys: &[
                "claim_boundary",
                "command",
                "evidence_repair_queues",
                "failed",
                "findings",
                "inventory",
                "outcomes",
                "scanner_limitations",
                "schema_id",
                "schema_version",
                "status",
                "summary",
                "tool",
                "trend",
            ],
        },
        ArtifactSample {
            name: "receipt",
            schema_name: "receipt",
            json: receipt_json,
            expected_command: "check",
            expected_top_level_keys: &[
                "advisory",
                "claim_boundary",
                "command",
                "counts",
                "enforcement",
                "evidence_repair_queues",
                "failed",
                "inventory",
                "mode",
                "policy_config",
                "scanner_limitations",
                "schema_id",
                "schema_version",
                "status",
                "tool",
                "tool_version",
            ],
        },
        ArtifactSample {
            name: "receipt_failed",
            schema_name: "receipt",
            json: failed_receipt_json,
            expected_command: "check",
            expected_top_level_keys: &[
                "advisory",
                "claim_boundary",
                "command",
                "counts",
                "evidence_repair_queues",
                "failed",
                "inventory",
                "scanner_limitations",
                "schema_id",
                "schema_version",
                "status",
                "tool",
            ],
        },
        ArtifactSample {
            name: "receipt_error",
            schema_name: "receipt",
            json: error_receipt_json,
            expected_command: "check",
            expected_top_level_keys: &[
                "advisory",
                "claim_boundary",
                "command",
                "counts",
                "diagnostic",
                "evidence_repair_queues",
                "failed",
                "inventory",
                "scanner_limitations",
                "schema_id",
                "schema_version",
                "status",
                "tool",
            ],
        },
        ArtifactSample {
            name: "diff",
            schema_name: "report",
            json: diff_json,
            expected_command: "diff",
            expected_top_level_keys: &[
                "claim_boundary",
                "command",
                "diff",
                "evidence_repair_queues",
                "failed",
                "findings",
                "inventory",
                "outcomes",
                "scanner_limitations",
                "schema_id",
                "schema_version",
                "status",
                "summary",
                "tool",
                "trend",
            ],
        },
    ]
}
