use super::ProposeContext;
use std::path::Path;

use crate::source_syntax_inventory_context;

pub(super) fn render_propose_summary(
    findings: usize,
    proposed_entries: usize,
    expires: &str,
    output: Option<&Path>,
) -> String {
    let mut out = String::new();
    out.push_str("cargo-allow propose summary\n");
    out.push_str(&format!("findings scanned: {findings}\n"));
    out.push_str(&format!(
        "baseline_debt entries proposed: {proposed_entries}\n"
    ));
    out.push_str("owner: unowned\n");
    out.push_str("classification: baseline_debt\n");
    out.push_str("reason: Generated by cargo-allow propose; requires human review.\n");
    out.push_str(&format!("expires: {expires}\n"));
    if let Some(output) = output {
        out.push_str(&format!("output: {}\n", output.display()));
    } else {
        out.push_str("output: stdout\n");
    }
    out.push_str(
        "claim boundary: proposal only; generated debt still requires human review and evidence.\n",
    );
    out
}

pub(super) fn render_propose_summary_json(
    findings: usize,
    proposed_entries: usize,
    expires: &str,
    output: Option<&Path>,
    force: bool,
    context: ProposeContext<'_>,
) -> String {
    let output_text = output.map(|path| path.display().to_string());
    allow_report::render_propose_json(allow_report::ProposeReport {
        inventory: source_syntax_inventory_context(
            context.inventory_source,
            context.source_tree_root,
            context.inventory_files,
        ),
        kind: context.kind_filter,
        expires,
        policy_output: output_text.as_deref(),
        force,
        findings_scanned: findings,
        baseline_debt_entries_proposed: proposed_entries,
    })
}
