use allow_core::{
    AllowEntry, CargoAllowResult, Finding, FindingKind, LastSeen, Lifecycle, MatchStatus,
    SimpleDate, json_escape,
};
use allow_match::{CheckMode, evaluate};
use allow_policy::render_policy;
use clap::{Parser, ValueEnum};
use std::path::{Path, PathBuf};

use crate::{
    RootArgs, load_world, option_json_string, selector_from_finding, source_tree_root_text,
    write_file, write_file_no_overwrite,
};

const BASELINE_DEBT_DEFAULT_DAYS: i64 = 67;

#[derive(Debug, Clone, Parser)]
pub(crate) struct ProposeArgs {
    #[command(flatten)]
    root: RootArgs,
    /// Policy config path.
    #[arg(long)]
    config: Option<PathBuf>,
    /// Filter findings by kind.
    #[arg(long)]
    kind: Option<String>,
    /// Include untracked files in addition to git-tracked files.
    #[arg(long)]
    include_untracked: bool,
    /// Expiry date for generated baseline_debt entries. Defaults to 67 days from today.
    #[arg(long)]
    expires: Option<String>,
    /// Write proposed policy to this path.
    #[arg(long)]
    write: Option<PathBuf>,
    /// Overwrite an existing output policy file.
    #[arg(long)]
    force: bool,
    /// Summary output format. Policy output remains TOML.
    #[arg(long, value_enum, default_value_t = ProposeSummaryFormat::Human)]
    summary_format: ProposeSummaryFormat,
    /// Write proposal summary to a file instead of stderr.
    #[arg(long)]
    summary_output: Option<PathBuf>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
enum ProposeSummaryFormat {
    Human,
    Json,
}

pub(crate) fn cmd_propose(args: &ProposeArgs) -> CargoAllowResult<()> {
    let (root, cfg, findings, inventory_facts) = load_world(
        args.root.root.as_deref(),
        args.config.as_deref(),
        false,
        args.kind.as_deref(),
        args.include_untracked,
    )?;
    let outcomes = evaluate(&cfg, &findings, CheckMode::Audit);
    let mut proposed = cfg.clone();
    let start = proposed.allow.len() + 1;
    let mut proposed_entries = 0;
    let expires = args.expires.clone().unwrap_or_else(default_baseline_expiry);
    for (n, outcome) in outcomes
        .iter()
        .filter(|o| o.status == MatchStatus::New)
        .enumerate()
    {
        if let Some(finding) = outcome.finding_index.and_then(|idx| findings.get(idx)) {
            proposed
                .allow
                .push(entry_from_finding(finding, start + n, &expires));
            proposed_entries += 1;
        }
    }
    let rendered = render_policy(&proposed);
    if let Some(path) = &args.write {
        write_file_no_overwrite(path, &rendered, args.force)?;
    } else {
        println!("{rendered}");
    }
    let root_text = source_tree_root_text(&root);
    let context = ProposeContext {
        inventory_source: inventory_facts.source.as_str(),
        source_tree_root: Some(&root_text),
        inventory_files: inventory_facts.files_scanned,
        kind_filter: args.kind.as_deref(),
    };
    let summary = match args.summary_format {
        ProposeSummaryFormat::Human => render_propose_summary(
            findings.len(),
            proposed_entries,
            expires.as_str(),
            args.write.as_deref(),
        ),
        ProposeSummaryFormat::Json => render_propose_summary_json(
            findings.len(),
            proposed_entries,
            expires.as_str(),
            args.write.as_deref(),
            args.force,
            context,
        ),
    };
    if let Some(path) = &args.summary_output {
        write_file(path, &summary)?;
    } else {
        eprintln!("{summary}");
    }
    Ok(())
}

#[derive(Debug, Clone, Copy)]
struct ProposeContext<'a> {
    inventory_source: &'a str,
    source_tree_root: Option<&'a str>,
    inventory_files: Option<usize>,
    kind_filter: Option<&'a str>,
}

impl Default for ProposeContext<'static> {
    fn default() -> Self {
        Self {
            inventory_source: "unknown",
            source_tree_root: None,
            inventory_files: None,
            kind_filter: None,
        }
    }
}

fn default_baseline_expiry() -> String {
    SimpleDate::today_utc_approx()
        .add_days(BASELINE_DEBT_DEFAULT_DAYS)
        .to_string()
}

fn render_propose_summary(
    findings: usize,
    proposed_entries: usize,
    expires: &str,
    output: Option<&Path>,
) -> String {
    let mut out = String::new();
    out.push_str("cargo-allow propose summary\n");
    out.push_str(&format!("findings scanned: {findings}\n"));
    out.push_str(&format!(
        "baseline_debt entries proposed: {proposed_entries}\n"
    ));
    out.push_str("owner: unowned\n");
    out.push_str("classification: baseline_debt\n");
    out.push_str("reason: Generated by cargo-allow propose; requires human review.\n");
    out.push_str(&format!("expires: {expires}\n"));
    if let Some(output) = output {
        out.push_str(&format!("output: {}\n", output.display()));
    } else {
        out.push_str("output: stdout\n");
    }
    out.push_str(
        "claim boundary: proposal only; generated debt still requires human review and evidence.\n",
    );
    out
}

fn render_propose_summary_json(
    findings: usize,
    proposed_entries: usize,
    expires: &str,
    output: Option<&Path>,
    force: bool,
    context: ProposeContext<'_>,
) -> String {
    let output_text = output.map(|path| path.display().to_string());
    let mut out = String::new();
    out.push_str("{\n");
    out.push_str(&format!(
        "  \"schema_version\": {},\n",
        allow_report::PROPOSE_SCHEMA_VERSION
    ));
    out.push_str(&format!(
        "  \"schema_id\": \"{}\",\n",
        allow_report::PROPOSE_SCHEMA_ID
    ));
    out.push_str("  \"tool\": \"cargo-allow\",\n");
    out.push_str("  \"command\": \"propose\",\n");
    out.push_str(&format!(
        "  \"claim_boundary\": {},\n",
        allow_report::render_claim_boundary_json()
    ));
    out.push_str(&format!(
        "  \"scanner_limitations\": {},\n",
        allow_report::render_scanner_limitations_json()
    ));
    out.push_str("  \"inventory\": ");
    out.push_str(&allow_report::render_inventory_json(
        allow_report::InventoryContext::source_syntax(
            context.inventory_source,
            context.source_tree_root,
            context.inventory_files,
        ),
        "  ",
    ));
    out.push_str(",\n");
    out.push_str("  \"options\": {\n");
    out.push_str(&format!(
        "    \"kind\": {},\n",
        option_json_string(context.kind_filter)
    ));
    out.push_str(&format!("    \"expires\": \"{}\",\n", json_escape(expires)));
    out.push_str(&format!(
        "    \"policy_output\": {},\n",
        option_json_string(output_text.as_deref())
    ));
    out.push_str(&format!("    \"force\": {}\n", force));
    out.push_str("  },\n");
    out.push_str("  \"summary\": {\n");
    out.push_str(&format!("    \"findings_scanned\": {findings},\n"));
    out.push_str(&format!(
        "    \"baseline_debt_entries_proposed\": {proposed_entries}\n"
    ));
    out.push_str("  },\n");
    out.push_str("  \"generated_entry_defaults\": {\n");
    out.push_str("    \"owner\": \"unowned\",\n");
    out.push_str("    \"classification\": \"baseline_debt\",\n");
    out.push_str("    \"reason\": \"Generated by cargo-allow propose; requires human review.\",\n");
    out.push_str(&format!("    \"expires\": \"{}\"\n", json_escape(expires)));
    out.push_str("  }\n");
    out.push_str("}\n");
    out
}

fn entry_from_finding(finding: &Finding, index: usize, expires: &str) -> AllowEntry {
    AllowEntry {
        id: format!("allow-{index:04}"),
        kind: finding.kind,
        family: finding.family.clone(),
        path: Some(finding.path.clone()),
        glob: None,
        owner: "unowned".to_string(),
        classification: "baseline_debt".to_string(),
        reason: "Generated by cargo-allow propose; requires human review.".to_string(),
        evidence: if finding.kind == FindingKind::Unsafe {
            vec!["TODO: add unsafe-review or boundary-test evidence".to_string()]
        } else {
            Vec::new()
        },
        links: Vec::new(),
        occurrence_limit: None,
        lifecycle: Lifecycle {
            created: Some(SimpleDate::today_utc_approx().to_string()),
            review_after: None,
            expires: Some(expires.to_string()),
        },
        selector: selector_from_finding(finding),
        last_seen: finding.span.as_ref().map(|s| LastSeen {
            line: s.line,
            column: s.column,
        }),
    }
}

#[cfg(test)]
pub(crate) fn sample_propose_json_for_contract_test() -> String {
    render_propose_summary_json(
        12,
        3,
        "2026-08-01",
        Some(Path::new("policy/allow.proposed.toml")),
        true,
        ProposeContext {
            inventory_source: "git_tracked",
            source_tree_root: Some("H:/Code/Rust/cargo-allow"),
            inventory_files: Some(51),
            kind_filter: Some("panic"),
        },
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{CargoAllowCli, CargoAllowCommand};
    use allow_core::{Span, StructuralIdentity};
    use clap::Parser;
    use std::path::Path;

    #[test]
    fn clap_parses_propose_force() {
        let parsed = CargoAllowCli::try_parse_from(argv(vec![
            "cargo-allow",
            "propose",
            "--write",
            "target/proposed.toml",
            "--force",
            "--summary-format",
            "json",
            "--summary-output",
            "target/propose-summary.json",
        ]))
        .unwrap_or_else(|err| std::panic::panic_any(format!("CLI should parse: {err}")));

        assert!(matches!(
            parsed.command,
            Some(CargoAllowCommand::Propose(ProposeArgs {
                write: Some(path),
                force: true,
                summary_format: ProposeSummaryFormat::Json,
                summary_output: Some(summary_output),
                ..
            })) if path == Path::new("target/proposed.toml")
                && summary_output == Path::new("target/propose-summary.json")
        ));
    }

    #[test]
    fn propose_summary_reports_generated_baseline_boundary() {
        let text = render_propose_summary(
            12,
            3,
            "2026-08-01",
            Some(Path::new("policy/allow.proposed.toml")),
        );

        assert!(text.contains("findings scanned: 12"));
        assert!(text.contains("baseline_debt entries proposed: 3"));
        assert!(text.contains("owner: unowned"));
        assert!(text.contains("classification: baseline_debt"));
        assert!(text.contains("output: policy/allow.proposed.toml"));
        assert!(text.contains("generated debt still requires human review"));
    }

    #[test]
    fn default_baseline_expiry_is_relative_to_current_date() {
        let before = SimpleDate::today_utc_approx().add_days(BASELINE_DEBT_DEFAULT_DAYS);
        let expires = default_baseline_expiry();
        let after = SimpleDate::today_utc_approx().add_days(BASELINE_DEBT_DEFAULT_DAYS);
        let parsed = SimpleDate::parse(&expires)
            .unwrap_or_else(|| std::panic::panic_any("default expiry should be a valid date"));

        assert!(
            before <= parsed && parsed <= after,
            "default baseline expiry should stay relative to the current UTC date"
        );
    }

    #[test]
    fn render_propose_summary_json_records_generated_baseline_boundary() {
        let json = sample_propose_json_for_contract_test();

        assert!(json.contains("\"schema_version\": 1"));
        assert!(json.contains(&format!(
            "\"schema_id\": \"{}\"",
            allow_report::PROPOSE_SCHEMA_ID
        )));
        assert!(json.contains("\"command\": \"propose\""));
        assert!(json.contains("\"claim_boundary\""));
        assert!(json.contains("\"scanner_limitations\""));
        assert!(json.contains("\"source\": \"git_tracked\""));
        assert!(json.contains("\"root\": \"H:/Code/Rust/cargo-allow\""));
        assert!(json.contains("\"files_scanned\": 51"));
        assert!(json.contains("\"kind\": \"panic\""));
        assert!(json.contains("\"policy_output\": \"policy/allow.proposed.toml\""));
        assert!(json.contains("\"force\": true"));
        assert!(json.contains("\"findings_scanned\": 12"));
        assert!(json.contains("\"baseline_debt_entries_proposed\": 3"));
        assert!(json.contains("\"owner\": \"unowned\""));
        assert!(json.contains("\"classification\": \"baseline_debt\""));
        assert!(json.contains("\"repository_code_not_executed\""));
    }

    #[test]
    fn proposed_baseline_entry_uses_current_created_date() {
        let before = SimpleDate::today_utc_approx();
        let entry = entry_from_finding(
            &Finding {
                kind: FindingKind::Panic,
                family: Some("unwrap".to_string()),
                path: "src/lib.rs".into(),
                span: Some(Span { line: 1, column: 1 }),
                identity: StructuralIdentity::new("rust", "method_call"),
                message: "test finding".to_string(),
            },
            1,
            "2026-08-01",
        );
        let after = SimpleDate::today_utc_approx();
        let created = entry
            .lifecycle
            .created
            .as_deref()
            .and_then(SimpleDate::parse)
            .unwrap_or_else(|| std::panic::panic_any("entry should have a valid created date"));

        assert!(
            before <= created && created <= after,
            "generated baseline entries should use the current UTC date"
        );
    }

    #[test]
    fn propose_schema_documents_current_contract() {
        let schema = include_str!("../../../docs/schemas/propose.schema.json");

        assert!(schema.contains(allow_report::PROPOSE_SCHEMA_ID));
        assert!(schema.contains("\"options\""));
        assert!(schema.contains("\"policy_output\""));
        assert!(schema.contains("\"baseline_debt_entries_proposed\""));
        assert!(schema.contains("\"generated_entry_defaults\""));
        assert!(schema.contains("\"scanner_limitations\""));
        assert!(schema.contains("\"scanner_limitation\""));
        assert!(schema.contains("\"cargo_metadata_not_invoked\""));
        assert!(schema.contains("\"repository_code_not_executed\""));
    }

    fn argv(items: Vec<&str>) -> Vec<String> {
        items.into_iter().map(String::from).collect()
    }
}
