//! File-operation and decision plan for one candidate-preparation
//! transaction (#3832).
//!
//! The compiler turns the #3831 semantic projection into the complete
//! ordered write set: one exact operation per selected surface, split
//! mechanically into deterministic generated bytes and judgment-bearing
//! rows that carry a typed `DecisionRequired`. It never applies anything:
//! applying belongs to the next child (#3833).
//!
//! Determinism law: equal inputs and decisions produce equal operations,
//! ordering, and digests. Ordering is by repository-relative path and then
//! semantic role, never by traversal order or wall-clock time.

use std::collections::BTreeMap;

use allow_core::sha256_v1_bytes;
use serde::{Deserialize, Serialize};

pub const CANDIDATE_OPERATION_PLAN_SCHEMA_V1: &str = "cargo-allow.candidate-operation-plan.v1";

/// The semantic owners whose operations the compiler requires. The CLI
/// gathers surface inputs from current authorities; the compiler rejects
/// an input set that omits any required owner class (omission control).
pub const REQUIRED_SURFACE_OWNERS: &[&str] = &[
    "workspace_manifest",
    "member_manifest",
    "cargo_lock",
    "package_topology",
    "support_matrix",
    "changie_corpus",
    "release_record",
    "github_release_note",
    "version_derived_surface",
    "governed_policy_plan",
];

pub const OPERATION_CLAIM_BOUNDARY_V1: &str = "A complete exact review plan for every file and repository decision in the cargo-allow candidate-preparation transaction. It makes the write set and unresolved judgment visible; it does not apply, qualify, authorize, or publish it.";

/// Write posture of one compiled operation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CandidateOperationPostureV1 {
    Create,
    Replace,
    Remove,
    NoOp,
    DecisionRequired,
    Conflict,
}

/// Current content state of one destination path.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CandidateContentStateV1 {
    pub exists: bool,
    pub digest: Option<String>,
}

impl CandidateContentStateV1 {
    pub fn absent() -> Self {
        Self {
            exists: false,
            digest: None,
        }
    }

    pub fn from_bytes(bytes: &[u8]) -> Self {
        Self {
            exists: true,
            digest: Some(sha256_v1_bytes(bytes)),
        }
    }
}

/// Collision/aliasing result for one destination, resolved through the
/// shared mutation-target authority by the caller.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum CandidateCollisionResultV1 {
    Clear,
    DuplicateDestination { detail: String },
    PathAlias { detail: String },
    CaseCollision { detail: String },
    SeparatorCollision { detail: String },
    SymlinkCollision { detail: String },
    Escape { detail: String },
}

impl CandidateCollisionResultV1 {
    pub const fn is_clear(&self) -> bool {
        matches!(self, Self::Clear)
    }
}

/// One compiled file operation with its full review context.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CandidateFileOperationV1 {
    /// Semantic owner class (`REQUIRED_SURFACE_OWNERS`).
    pub owner: String,
    /// Role within the owner (e.g. `package_version`, `candidate_fields`).
    pub role: String,
    /// Repository-relative destination path.
    pub path: String,
    pub current: CandidateContentStateV1,
    /// Digest of the deterministically rendered prospective bytes; `None`
    /// for judgment-bearing rows.
    pub prospective_digest: Option<String>,
    pub posture: CandidateOperationPostureV1,
    /// Producer identity of the generated bytes (or the decision source).
    pub producer: String,
    /// `true` only when the prospective bytes are fully deterministic.
    pub deterministic: bool,
    pub collision: CandidateCollisionResultV1,
    /// Where a rollback can restore this destination from (e.g. the
    /// current-content digest, or a named source input).
    pub rollback_source: Option<String>,
    pub validation_obligations: Vec<String>,
}

/// One judgment the plan cannot make, bound to the operations it blocks.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CandidateSurfaceDecisionV1 {
    pub decision_id: String,
    pub question: String,
    pub owner: String,
    /// `owner:path` keys of the operations this decision resolves.
    pub affected_operations: Vec<String>,
    /// Named inputs whose absence or staleness produced this decision.
    pub missing_inputs: Vec<String>,
}

/// The compiled, ordered operation plan (#3832). Additive over the #3831
/// plan; older results without these fields stay valid.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CandidateOperationPlanV1 {
    pub schema: &'static str,
    /// Owner classes the compiler required for this plan.
    pub required_owners: Vec<String>,
    pub operations: Vec<CandidateFileOperationV1>,
    pub decisions: Vec<CandidateSurfaceDecisionV1>,
    /// Digest over the canonical serialization of operations and
    /// decisions, independent of the #3831 plan digest.
    pub operations_digest: String,
    pub claim_boundary: &'static str,
}

/// One surface input gathered by the caller from a live authority.
#[derive(Debug, Clone)]
pub struct CandidateSurfaceInputV1 {
    pub owner: String,
    pub role: String,
    pub path: String,
    pub current: CandidateContentStateV1,
    /// Deterministically rendered prospective bytes, when this surface is
    /// generated. `None` for judgment-bearing surfaces.
    pub prospective_bytes: Option<Vec<u8>>,
    /// The judgment required before bytes can exist. Exactly one of
    /// `prospective_bytes` or `judgment` must be present.
    pub judgment: Option<CandidateSurfaceDecisionV1>,
    pub collision: CandidateCollisionResultV1,
    pub rollback_source: Option<String>,
    pub validation_obligations: Vec<String>,
}

/// Everything the compiler needs: the gathered surface inputs. The #3831
/// plan stays the caller's context; the compiled rows are self-describing.
#[derive(Debug, Clone)]
pub struct CandidateOperationCompilerInput {
    pub surfaces: Vec<CandidateSurfaceInputV1>,
}

/// Compile the complete ordered operation plan. Never panics; omissions
/// and conflicts surface as explicit rows.
pub fn compile_candidate_operations(
    input: CandidateOperationCompilerInput,
) -> CandidateOperationPlanV1 {
    let mut decisions: Vec<CandidateSurfaceDecisionV1> = Vec::new();
    let mut operations: Vec<CandidateFileOperationV1> = Vec::new();
    let mut conflicts: Vec<String> = Vec::new();

    // Omission control: every required owner must appear among the inputs.
    let mut seen_owners: BTreeMap<&str, ()> = BTreeMap::new();
    for surface in &input.surfaces {
        seen_owners.insert(surface.owner.as_str(), ());
    }
    let mut missing_owners: Vec<String> = Vec::new();
    for required in REQUIRED_SURFACE_OWNERS {
        if !seen_owners.contains_key(*required) {
            missing_owners.push((*required).to_string());
        }
    }
    if !missing_owners.is_empty() {
        conflicts.push(format!(
            "the compiled surface set omits required owner classes: {}",
            missing_owners.join(", ")
        ));
    }

    for surface in &input.surfaces {
        let path_key = format!("{}:{}", surface.owner, surface.path);
        let (posture, prospective_digest, deterministic, producer) =
            if !surface.collision.is_clear() {
                (
                    CandidateOperationPostureV1::Conflict,
                    None,
                    false,
                    "candidate-preparation-operations/1".to_string(),
                )
            } else if let Some(bytes) = &surface.prospective_bytes {
                let digest = sha256_v1_bytes(bytes);
                let unchanged = surface
                    .current
                    .digest
                    .as_deref()
                    .is_some_and(|current| current == digest);
                let posture = match (surface.current.exists, unchanged) {
                    (false, _) => CandidateOperationPostureV1::Create,
                    (true, true) => CandidateOperationPostureV1::NoOp,
                    (true, false) => CandidateOperationPostureV1::Replace,
                };
                (
                    posture,
                    Some(digest),
                    true,
                    "candidate-preparation-operations/1".to_string(),
                )
            } else if let Some(judgment) = &surface.judgment {
                decisions.push(CandidateSurfaceDecisionV1 {
                    affected_operations: if judgment.affected_operations.is_empty() {
                        vec![path_key.clone()]
                    } else {
                        judgment.affected_operations.clone()
                    },
                    ..judgment.clone()
                });
                (
                    CandidateOperationPostureV1::DecisionRequired,
                    None,
                    false,
                    format!("decision:{}", judgment.decision_id),
                )
            } else {
                conflicts.push(format!(
                    "surface {path_key} carries neither prospective bytes nor a judgment"
                ));
                (
                    CandidateOperationPostureV1::Conflict,
                    None,
                    false,
                    "candidate-preparation-operations/1".to_string(),
                )
            };

        operations.push(CandidateFileOperationV1 {
            owner: surface.owner.clone(),
            role: surface.role.clone(),
            path: surface.path.clone(),
            current: surface.current.clone(),
            prospective_digest,
            posture,
            producer,
            deterministic,
            collision: surface.collision.clone(),
            rollback_source: surface.rollback_source.clone(),
            validation_obligations: surface.validation_obligations.clone(),
        });
    }

    for conflict in &conflicts {
        decisions.push(CandidateSurfaceDecisionV1 {
            decision_id: "operation-conflict".to_string(),
            question: conflict.clone(),
            owner: "release-operator".to_string(),
            affected_operations: Vec::new(),
            missing_inputs: Vec::new(),
        });
    }

    // Deterministic ordering: path, then owner, then role.
    operations.sort_by(|a, b| {
        (a.path.clone(), a.owner.clone(), a.role.clone()).cmp(&(
            b.path.clone(),
            b.owner.clone(),
            b.role.clone(),
        ))
    });
    decisions.sort_by(|a, b| a.decision_id.cmp(&b.decision_id));

    let draft = CandidateOperationPlanV1 {
        schema: CANDIDATE_OPERATION_PLAN_SCHEMA_V1,
        required_owners: REQUIRED_SURFACE_OWNERS
            .iter()
            .map(|owner| (*owner).to_string())
            .collect(),
        operations,
        decisions,
        operations_digest: String::new(),
        claim_boundary: OPERATION_CLAIM_BOUNDARY_V1,
    };
    let digest = sha256_v1_bytes(
        serde_json::to_string(&draft)
            .expect("candidate operation plan must serialize canonically")
            .as_bytes(),
    );
    CandidateOperationPlanV1 {
        operations_digest: digest,
        ..draft
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn surface(
        owner: &str,
        path: &str,
        current_bytes: Option<&[u8]>,
        prospective: Option<Vec<u8>>,
        judgment: Option<CandidateSurfaceDecisionV1>,
    ) -> CandidateSurfaceInputV1 {
        CandidateSurfaceInputV1 {
            owner: owner.to_string(),
            role: "role".to_string(),
            path: path.to_string(),
            current: match current_bytes {
                Some(bytes) => CandidateContentStateV1::from_bytes(bytes),
                None => CandidateContentStateV1::absent(),
            },
            prospective_bytes: prospective,
            judgment,
            collision: CandidateCollisionResultV1::Clear,
            rollback_source: None,
            validation_obligations: Vec::new(),
        }
    }

    fn judgment(id: &str, question: &str) -> Option<CandidateSurfaceDecisionV1> {
        Some(CandidateSurfaceDecisionV1 {
            decision_id: id.to_string(),
            question: question.to_string(),
            owner: "release-operator".to_string(),
            affected_operations: Vec::new(),
            missing_inputs: Vec::new(),
        })
    }

    fn full_surface_set() -> Vec<CandidateSurfaceInputV1> {
        REQUIRED_SURFACE_OWNERS
            .iter()
            .map(|owner| {
                surface(
                    owner,
                    &format!("paths/{owner}.txt"),
                    Some(b"current".as_slice()),
                    Some(b"prospective".to_vec()),
                    None,
                )
            })
            .collect()
    }

    #[test]
    fn generated_surfaces_compile_to_exact_postures() {
        let mut surfaces = full_surface_set();
        // A brand-new generated file is a Create.
        surfaces.push(surface(
            "workspace_manifest",
            "paths/new.txt",
            None,
            Some(b"created".to_vec()),
            None,
        ));
        // Identical current and prospective bytes are a NoOp.
        surfaces.push(surface(
            "member_manifest",
            "paths/same.txt",
            Some(b"same".as_slice()),
            Some(b"same".to_vec()),
            None,
        ));
        let compiled = compile_candidate_operations(CandidateOperationCompilerInput { surfaces });
        let postures: Vec<(String, CandidateOperationPostureV1)> = compiled
            .operations
            .iter()
            .map(|operation| (operation.path.clone(), operation.posture))
            .collect();
        assert!(postures.contains(&(
            "paths/new.txt".to_string(),
            CandidateOperationPostureV1::Create
        )));
        assert!(postures.contains(&(
            "paths/same.txt".to_string(),
            CandidateOperationPostureV1::NoOp
        )));
        assert_eq!(
            compiled
                .operations
                .iter()
                .filter(|operation| operation.posture == CandidateOperationPostureV1::Replace)
                .count(),
            REQUIRED_SURFACE_OWNERS.len()
        );
        assert!(compiled.decisions.is_empty());
        assert!(!compiled.operations_digest.is_empty());
    }

    #[test]
    fn omission_of_a_required_owner_is_a_named_conflict() {
        let mut omitted = full_surface_set();
        omitted.retain(|surface| surface.owner != "cargo_lock");
        let compiled =
            compile_candidate_operations(CandidateOperationCompilerInput { surfaces: omitted });
        assert!(compiled.decisions.iter().any(|decision| {
            decision
                .question
                .contains("omits required owner classes: cargo_lock")
        }));
    }

    #[test]
    fn judgment_surfaces_are_decision_required_and_never_deterministic() {
        let mut surfaces = full_surface_set();
        surfaces.push(surface(
            "release_record",
            "paths/prose.md",
            Some(b"old".as_slice()),
            None,
            judgment("release-prose", "Author the final release prose."),
        ));
        let compiled = compile_candidate_operations(CandidateOperationCompilerInput { surfaces });
        let row = compiled
            .operations
            .iter()
            .find(|operation| operation.path == "paths/prose.md")
            .expect("row exists");
        assert_eq!(row.posture, CandidateOperationPostureV1::DecisionRequired);
        assert!(!row.deterministic);
        assert!(row.prospective_digest.is_none());
        assert!(compiled.decisions.iter().any(|decision| {
            decision.decision_id == "release-prose"
                && decision
                    .affected_operations
                    .contains(&"release_record:paths/prose.md".to_string())
        }));
    }

    #[test]
    fn collisions_are_conflicts_regardless_of_bytes() {
        let mut surfaces = full_surface_set();
        let mut collided = surface(
            "workspace_manifest",
            "Cargo.toml",
            Some(b"current".as_slice()),
            Some(b"prospective".to_vec()),
            None,
        );
        collided.collision = CandidateCollisionResultV1::CaseCollision {
            detail: "cargo.toml differs only by case".to_string(),
        };
        surfaces.push(collided);
        let compiled = compile_candidate_operations(CandidateOperationCompilerInput { surfaces });
        let row = compiled
            .operations
            .iter()
            .find(|operation| operation.path == "Cargo.toml")
            .expect("row exists");
        assert_eq!(row.posture, CandidateOperationPostureV1::Conflict);
        assert!(!row.deterministic);
    }

    #[test]
    fn a_surface_with_neither_bytes_nor_judgment_conflicts() {
        let mut surfaces = full_surface_set();
        surfaces.push(surface(
            "cargo_lock",
            "paths/lock",
            Some(b"c".as_slice()),
            None,
            None,
        ));
        let compiled = compile_candidate_operations(CandidateOperationCompilerInput { surfaces });
        assert!(compiled.decisions.iter().any(|decision| {
            decision
                .question
                .contains("neither prospective bytes nor a judgment")
        }));
    }

    #[test]
    fn equal_inputs_produce_equal_order_and_digest() {
        let first = compile_candidate_operations(CandidateOperationCompilerInput {
            surfaces: full_surface_set(),
        });
        let second = compile_candidate_operations(CandidateOperationCompilerInput {
            surfaces: full_surface_set(),
        });
        assert_eq!(first.operations_digest, second.operations_digest);
        assert_eq!(first.operations, second.operations);
        assert_eq!(
            first
                .operations
                .iter()
                .map(|o| o.path.as_str())
                .collect::<Vec<_>>(),
            second
                .operations
                .iter()
                .map(|o| o.path.as_str())
                .collect::<Vec<_>>(),
        );
    }
}
