#![allow(dead_code)]

use crate::CLAIM_BOUNDARY_TEXT;

/// Schema constants for the release manifest artifact.
pub const RELEASE_MANIFEST_SCHEMA_VERSION: u32 = 1;
pub const RELEASE_MANIFEST_SCHEMA_ID: &str = "cargo-allow.release-manifest.v1";

/// The claim boundary text included in every release manifest.
pub const RELEASE_MANIFEST_CLAIM_BOUNDARY: &str = CLAIM_BOUNDARY_TEXT;

/// Structured payload for `cargo-allow.release-manifest.v1`.
///
/// Binds the reviewed source candidate, package graph, registry artifacts,
/// authentication path, and smoke receipts into one deterministic release
/// identity. Generated by the release workflow after all publish and smoke
/// steps complete. Consumed by verification tools and release notes.
///
/// All fields use typed serialization via `serde_json` with deterministic
/// field ordering. Equal semantic inputs produce equal manifest bytes except
/// for `generated_at`, which records the wall-clock generation time.
#[derive(Debug, Clone, Eq, PartialEq, serde::Deserialize, serde::Serialize)]
pub struct ReleaseManifestV1 {
    /// Schema identifier (`cargo-allow.release-manifest.v1`).
    pub schema_id: String,
    /// Schema generation (1).
    pub schema_version: u32,
    /// cargo-allow tool version that generated this manifest.
    pub tool_version: String,

    // -- Repository identity --
    /// Repository full name (e.g. `EffortlessMetrics/cargo-allow`).
    pub repository: String,
    /// Git tag ref (e.g. `v0.2.0`).
    pub tag: String,
    /// Commit SHA the tag points to.
    pub commit: String,
    /// Tree SHA of the tagged commit.
    pub tree: String,

    // -- Release version --
    /// Workspace version string (e.g. `0.2.0`).
    pub version: String,

    // -- Source candidate identity --
    /// SHA-256 of the source candidate report, if available.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_candidate_digest: Option<String>,

    // -- Crates --
    /// Ordered list of crates in publish/dependency order.
    pub crates: Vec<ManifestCrate>,

    // -- Authentication --
    /// How the release authenticated with crates.io: `oidc` or `secret`.
    pub auth_source: String,
    /// GitHub Actions workflow run ID.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workflow_run_id: Option<u64>,

    // -- Platform / MSRV matrix --
    /// Declared minimum supported Rust version.
    pub msrv: String,
    /// Platforms proven by smoke: e.g. `["linux"]`.
    pub platforms_proven: Vec<String>,

    // -- Schema/tool generations --
    /// Schema generations in effect at release time.
    pub generations: ManifestGenerations,

    // -- Known limitations --
    /// Explicit limitations of this release.
    pub limitations: Vec<String>,

    // -- Claim boundary --
    /// The cargo-allow claim boundary text.
    pub claim_boundary: String,

    // -- Generation metadata --
    /// ISO 8601 timestamp of manifest generation.
    pub generated_at: String,
}

/// One crate entry in the release manifest.
#[derive(Debug, Clone, Eq, PartialEq, serde::Deserialize, serde::Serialize)]
pub struct ManifestCrate {
    /// Crate name (e.g. `cargo-allow`).
    pub name: String,
    /// Published version.
    pub version: String,
    /// SHA-256 of the `.crate` file (`sha256:<hex>`), if computed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub crate_checksum: Option<String>,
    /// crates.io registry checksum, if verified.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub registry_checksum: Option<String>,
}

/// Schema/tool generation snapshot at release time.
#[derive(Debug, Clone, Eq, PartialEq, serde::Deserialize, serde::Serialize)]
pub struct ManifestGenerations {
    /// Release manifest schema generation.
    pub release_manifest: u32,
    /// Add-finding-plan schema generation.
    pub add_finding_plan: u32,
    /// Mutation-receipt schema generation.
    pub mutation_receipt: u32,
}

/// Render the manifest as deterministic JSON with stable key ordering.
pub fn render_release_manifest_json(
    manifest: &ReleaseManifestV1,
) -> Result<String, serde_json::Error> {
    serde_json::to_string_pretty(manifest)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::error::Error;

    fn field<'a>(
        value: &'a serde_json::Value,
        name: &str,
    ) -> Result<&'a serde_json::Value, String> {
        value
            .get(name)
            .ok_or_else(|| format!("manifest JSON omitted `{name}`"))
    }

    #[test]
    fn release_manifest_v1_serializes_with_required_fields() -> Result<(), Box<dyn Error>> {
        let manifest = ReleaseManifestV1 {
            schema_id: RELEASE_MANIFEST_SCHEMA_ID.to_string(),
            schema_version: RELEASE_MANIFEST_SCHEMA_VERSION,
            tool_version: "0.2.0".to_string(),
            repository: "EffortlessMetrics/cargo-allow".to_string(),
            tag: "v0.2.0".to_string(),
            commit: "abc123".to_string(),
            tree: "def456".to_string(),
            version: "0.2.0".to_string(),
            source_candidate_digest: None,
            crates: vec![ManifestCrate {
                name: "cargo-allow".to_string(),
                version: "0.2.0".to_string(),
                crate_checksum: Some("sha256:deadbeef".to_string()),
                registry_checksum: None,
            }],
            auth_source: "oidc".to_string(),
            workflow_run_id: Some(12345),
            msrv: "1.95".to_string(),
            platforms_proven: vec!["linux".to_string()],
            generations: ManifestGenerations {
                release_manifest: 1,
                add_finding_plan: 1,
                mutation_receipt: 1,
            },
            limitations: vec!["source-tree-only scan".to_string()],
            claim_boundary: RELEASE_MANIFEST_CLAIM_BOUNDARY.to_string(),
            generated_at: "2026-07-19T12:00:00Z".to_string(),
        };

        let json = render_release_manifest_json(&manifest)?;
        let parsed: serde_json::Value = serde_json::from_str(&json)?;
        let decoded: ReleaseManifestV1 = serde_json::from_str(&json)?;
        if decoded != manifest {
            return Err("manifest JSON did not round-trip through Deserialize".into());
        }

        let crates = field(&parsed, "crates")?
            .as_array()
            .ok_or("manifest crates was not a JSON array")?;
        let first_crate = crates
            .first()
            .ok_or("manifest crates array was unexpectedly empty")?;
        if field(&parsed, "schema_id")? != RELEASE_MANIFEST_SCHEMA_ID
            || field(&parsed, "schema_version")? != 1
            || field(&parsed, "version")? != "0.2.0"
            || field(first_crate, "name")? != "cargo-allow"
            || field(&parsed, "auth_source")? != "oidc"
            || field(&parsed, "msrv")? != "1.95"
        {
            return Err("manifest JSON omitted or changed a required field".into());
        }
        let claim_boundary = parsed
            .get("claim_boundary")
            .and_then(serde_json::Value::as_str)
            .ok_or("manifest claim boundary was not a JSON string")?;
        if claim_boundary.is_empty() {
            return Err("manifest claim boundary was empty".into());
        }
        Ok(())
    }

    #[test]
    fn release_manifest_v1_skips_none_fields() -> Result<(), Box<dyn Error>> {
        let manifest = ReleaseManifestV1 {
            schema_id: RELEASE_MANIFEST_SCHEMA_ID.to_string(),
            schema_version: RELEASE_MANIFEST_SCHEMA_VERSION,
            tool_version: "0.2.0".to_string(),
            repository: "test".to_string(),
            tag: "v0.2.0".to_string(),
            commit: "abc".to_string(),
            tree: "def".to_string(),
            version: "0.2.0".to_string(),
            source_candidate_digest: None,
            crates: vec![],
            auth_source: "oidc".to_string(),
            workflow_run_id: None,
            msrv: "1.95".to_string(),
            platforms_proven: vec![],
            generations: ManifestGenerations {
                release_manifest: 1,
                add_finding_plan: 1,
                mutation_receipt: 1,
            },
            limitations: vec![],
            claim_boundary: RELEASE_MANIFEST_CLAIM_BOUNDARY.to_string(),
            generated_at: "2026-07-19T12:00:00Z".to_string(),
        };

        let json = render_release_manifest_json(&manifest)?;
        let parsed: serde_json::Value = serde_json::from_str(&json)?;

        // Fields with skip_serializing_if should be absent when None
        if parsed.get("source_candidate_digest").is_some()
            || parsed.get("workflow_run_id").is_some()
        {
            return Err("None-valued optional fields were serialized".into());
        }
        Ok(())
    }
}
