#!/usr/bin/env bash
# ProofCandidateInstallSmokeV1 (#2589-B).
#
# Packages the six-crate proof stack, extracts each .crate outside the
# workspace, installs cargo-proof from the extracted tree via patched path
# resolution, verifies the isolated binary surface, and denies workspace
# source-checkout / target/debug leakage during the decisive install.
#
# Does not: publish; invoke cargo test or proof runners; depend on cargo-allow
# sibling crate reads during the installed journey.
#
# Usage:
#   bash scripts/proof-candidate-smoke.sh
#
# Optional:
#   WORK_DIR=<path>      work root (default: target/proof-candidate-smoke)
#   SKIP_PACKAGE=1       reuse WORK_DIR/packages without re-packing
#   ALLOW_DIRTY=1        pass --allow-dirty to cargo package (local debug only)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT}"

work_dir="${WORK_DIR:-${ROOT}/target/proof-candidate-smoke}"
packages_dir="${work_dir}/packages"
offline_root="${OFFLINE_ROOT:-$(mktemp -d "${TMPDIR:-/tmp}/cargo-proof-ics-offline.XXXXXX")}"
extracted_dir="${offline_root}/extracted"
cargo_home="${offline_root}/cargo-home"
target_dir="${offline_root}/target"
install_root="${offline_root}/install"
receipt="${work_dir}/proof-candidate-smoke.receipt.json"
crate_set_fixture="${ROOT}/docs/dogfood/fixtures/release/proof-candidate-crate-set.toml"
schema_id="cargo-allow.proof-candidate-smoke.v1"
crate_set_schema_id="cargo-allow.proof-candidate-crate-set.v1"
crates_path="${ROOT}/crates"
crates_stash="${work_dir}/crates-source-stash"

restore_source_checkout() {
  if [[ -d "${crates_stash}" && ! -e "${crates_path}" ]]; then
    mv "${crates_stash}" "${crates_path}"
  fi
}

cleanup_offline() {
  restore_source_checkout
  if [[ "${KEEP_OFFLINE:-0}" != "1" ]]; then
    rm -rf "${offline_root}"
  fi
}
trap cleanup_offline EXIT

log() {
  printf 'proof-candidate-smoke: %s\n' "$*"
}

fail() {
  printf 'proof-candidate-smoke: error: %s\n' "$*" >&2
  exit 1
}

command -v cargo >/dev/null 2>&1 || fail "cargo is required"
command -v python3 >/dev/null 2>&1 || fail "python3 is required"
command -v tar >/dev/null 2>&1 || fail "tar is required"

read_workspace_version() {
  awk '
    /^\[workspace\.package\]/ { in_ws = 1; next }
    /^\[/ { if (in_ws) exit }
    in_ws && /^version = / {
      gsub(/^version = "/, "", $0)
      gsub(/".*$/, "", $0)
      print $0
      exit
    }
  ' Cargo.toml
}

# Resolve the current workspace directory for a Cargo package identity.
# The first-publication name correction keeps source paths stable (#3440).
workspace_dir_for_package() {
  case "$1" in
    intent-compiler) printf '%s\n' "intent-engine" ;;
    proof-orchestrator) printf '%s\n' "proof-engine" ;;
    *) printf '%s\n' "$1" ;;
  esac
}

# Resolve package versions after the workspace package split.
read_crate_version() {
  local crate="$1"
  local workspace_dir
  local line
  workspace_dir="$(workspace_dir_for_package "${crate}")"
  line="$(grep -m1 '^version' "crates/${workspace_dir}/Cargo.toml" 2>/dev/null)" || true
  if [[ "${line}" == "version.workspace = true" ]]; then
    read_workspace_version
  else
    echo "${line}" | sed 's/^version = "//; s/"$//'
  fi
}

mapfile -t crates < <(
  python3 - "${crate_set_fixture}" <<'PY'
import sys
from pathlib import Path

text = Path(sys.argv[1]).read_text(encoding="utf-8")
in_list = False
for line in text.splitlines():
    stripped = line.strip().strip("\r")
    if stripped.startswith("crates"):
        in_list = True
        continue
    if in_list:
        if stripped.startswith("]"):
            break
        if stripped.startswith('"'):
            name = stripped.strip(",").strip('"').strip()
            if name:
                print(name)
PY
)
for i in "${!crates[@]}"; do
  crates[$i]="${crates[$i]//$'\r'/}"
done

[[ "${#crates[@]}" -eq 4 ]] || fail "expected 4 crates from ${crate_set_fixture}, got ${#crates[@]}"

version="$(read_workspace_version)"
[[ -n "${version}" ]] || fail "could not read workspace.package.version"

git_head=""
if command -v git >/dev/null 2>&1 && git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  git_head="$(git rev-parse HEAD 2>/dev/null || true)"
fi

to_cargo_path() {
  local input="$1"
  if command -v cygpath >/dev/null 2>&1; then
    cygpath -m "${input}"
  else
    printf '%s\n' "${input}"
  fi
}

assert_no_path_deps() {
  local tree="$1"
  local label="$2"
  local hits
  hits="$(
    grep -R --include='Cargo.toml' -nE 'path = "' "${tree}" 2>/dev/null \
      | grep -v '^Binary' \
      | grep -vE 'path = "(src|benches|examples|tests)/' \
      || true
  )"
  if [[ -n "${hits}" ]]; then
    printf '%s\n' "${hits}"
    fail "packaged ${label} still contains path dependencies"
  fi
}

write_patch_config() {
  local config_path="$1"
  shift
  local -a patched=("$@")
  {
    echo '# Generated by scripts/proof-candidate-smoke.sh'
    echo '[patch.crates-io]'
    for patched_crate in "${patched[@]}"; do
      crate_version="$(read_crate_version "${patched_crate}")"
      path_value="$(to_cargo_path "${extracted_dir}/${patched_crate}-${crate_version}")"
      printf '%s = { path = "%s" }\n' "${patched_crate}" "${path_value}"
    done
  } >"${config_path}"
}

sha256_file() {
  local file="$1"
  local native="$1"
  if command -v cygpath >/dev/null 2>&1; then
    native="$(cygpath -w "${file}")"
  fi
  python3 -c "import hashlib,sys; print(hashlib.sha256(open(sys.argv[1],'rb').read()).hexdigest())" "${native}"
}

rm -rf "${work_dir}"
mkdir -p "${packages_dir}" "${extracted_dir}" "${cargo_home}" "${target_dir}" "${install_root}"

export CARGO_TARGET_DIR="${target_dir}"

declare -a crate_records=()
declare -a dependency_crates=("${crates[@]:0:$(( ${#crates[@]} - 1 ))}")

if [[ "${SKIP_PACKAGE:-0}" == "1" ]]; then
  shopt -s nullglob
  staged=("${packages_dir}"/*.crate)
  shopt -u nullglob
  [[ "${#staged[@]}" -gt 0 ]] || fail "SKIP_PACKAGE=1 but no .crate files under ${packages_dir}"
  for crate in "${crates[@]}"; do
    crate_version="$(read_crate_version "${crate}")"
    src="${packages_dir}/${crate}-${crate_version}.crate"
    [[ -f "${src}" ]] || fail "missing ${src}"
    dest="${extracted_dir}/${crate}-${crate_version}"
    rm -rf "${dest}"
    mkdir -p "${dest}"
    tar --force-local -xzf "${src}" -C "${extracted_dir}"
    assert_no_path_deps "${dest}" "${crate}"
    digest="$(sha256_file "${src}")"
    size="$(wc -c <"${src}" | tr -d ' \r')"
    crate_records+=("${crate}|${crate_version}|${crate}-${crate_version}.crate|${digest}|${size}|${crate}-${crate_version}")
  done
else
  for idx in "${!dependency_crates[@]}"; do
    crate="${dependency_crates[$idx]}"
    if [[ "${idx}" -eq 0 ]]; then
      log "packaging dependency crate ${crate} from workspace (no patch)"
      unset CARGO_HOME
      cargo package -p "${crate}" --allow-dirty
    else
      log "packaging dependency crate ${crate} with extracted patch (${idx} prior)"
      export CARGO_HOME="${cargo_home}"
      write_patch_config "${cargo_home}/config.toml" "${dependency_crates[@]:0:${idx}}"
      cargo package -p "${crate}" --allow-dirty
    fi
    crate_version="$(read_crate_version "${crate}")"
    src="${target_dir}/package/${crate}-${crate_version}.crate"
    [[ -f "${src}" ]] || fail "missing packaged crate ${src}"
    cp "${src}" "${packages_dir}/"
    dest="${extracted_dir}/${crate}-${crate_version}"
    rm -rf "${dest}"
    mkdir -p "${dest}"
    tar --force-local -xzf "${src}" -C "${extracted_dir}"
    assert_no_path_deps "${dest}" "${crate}"
    digest="$(sha256_file "${src}")"
    size="$(wc -c <"${src}" | tr -d ' \r')"
    crate_records+=("${crate}|${crate_version}|${crate}-${crate_version}.crate|${digest}|${size}|${crate}-${crate_version}")
    log "packaged ${crate}-${crate_version}.crate sha256=${digest}"
  done
  log "packaging cargo-proof with full extracted dependency patch"
  export CARGO_HOME="${cargo_home}"
  write_patch_config "${cargo_home}/config.toml" "${dependency_crates[@]}"
  cargo package -p cargo-proof --allow-dirty
  crate="cargo-proof"
  crate_version="$(read_crate_version "${crate}")"
  src="${target_dir}/package/${crate}-${crate_version}.crate"
  [[ -f "${src}" ]] || fail "missing packaged crate ${src}"
  cp "${src}" "${packages_dir}/"
  dest="${extracted_dir}/${crate}-${crate_version}"
  rm -rf "${dest}"
  mkdir -p "${dest}"
  tar --force-local -xzf "${src}" -C "${extracted_dir}"
  assert_no_path_deps "${dest}" "${crate}"
  digest="$(sha256_file "${src}")"
  size="$(wc -c <"${src}" | tr -d ' \r')"
  crate_records+=("${crate}|${crate_version}|${crate}-${crate_version}.crate|${digest}|${size}|${crate}-${crate_version}")
  log "packaged ${crate}-${crate_version}.crate sha256=${digest}"
fi

proof_version="$(read_crate_version cargo-proof)"
extracted_bin_pkg="${extracted_dir}/cargo-proof-${proof_version}"
[[ -d "${extracted_bin_pkg}" ]] || fail "missing extracted cargo-proof package"

log "verifying extracted cargo-proof root is outside the workspace"
root_meta_path="${offline_root}/root-metadata.json"
cargo metadata --format-version 1 --no-deps --manifest-path "${extracted_bin_pkg}/Cargo.toml" \
  >"${root_meta_path}" 2>/dev/null \
  || cargo metadata --format-version 1 --manifest-path "${extracted_bin_pkg}/Cargo.toml" \
    >"${root_meta_path}"
ROOT_NATIVE="$(to_cargo_path "${ROOT}")"
EXTRACTED_NATIVE="$(to_cargo_path "${extracted_dir}")"
python3 - "${root_meta_path}" "${ROOT_NATIVE}" "${EXTRACTED_NATIVE}" <<'PY'
import json, sys
from pathlib import Path

meta = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
root = Path(sys.argv[2]).resolve()
extracted = Path(sys.argv[3]).resolve()
packages = {p["name"]: p for p in meta.get("packages", [])}
root_pkg = packages.get("cargo-proof")
if root_pkg is None:
    raise SystemExit("cargo-proof missing from metadata packages")
manifest = Path(root_pkg["manifest_path"]).resolve()
try:
    manifest.relative_to(extracted)
except ValueError as err:
    raise SystemExit(f"cargo-proof manifest not under extracted tree: {manifest}") from err
crates_dir = root / "crates"
if crates_dir in manifest.parents or str(manifest).startswith(str(crates_dir)):
    raise SystemExit(f"WorkspacePathLeak: manifest under workspace {manifest}")
print("metadata_root_ok")
PY

write_patch_config "${cargo_home}/config.toml" "${crates[@]}"

log "denying workspace source checkout (renaming crates/) during decisive install"
[[ -d "${crates_path}" ]] || fail "expected workspace crates/ at ${crates_path}"
restore_source_checkout
rm -rf "${crates_stash}"
mv "${crates_path}" "${crates_stash}"
[[ ! -e "${crates_path}" ]] || fail "crates/ still present after stash for source-checkout denial"

workspace_debug_bin="${ROOT}/target/debug/cargo-proof"
workspace_debug_bin_exe="${workspace_debug_bin}.exe"
if [[ -x "${workspace_debug_bin}" || -f "${workspace_debug_bin}" ]]; then
  log "note: workspace target/debug/cargo-proof exists; install must not use it"
fi

rm -rf "${install_root}"
mkdir -p "${install_root}"
set +e
cargo install \
  --path "${extracted_bin_pkg}" \
  --locked \
  --root "${install_root}" \
  --force
install_code=$?
set -e
restore_source_checkout
[[ -d "${crates_path}" ]] || fail "failed to restore crates/ after decisive install"
[[ ! -e "${crates_stash}" ]] || fail "crates stash still present after restore"
[[ "${install_code}" -eq 0 ]] || fail "cargo install from extracted cargo-proof failed (exit ${install_code})"

cargo_bin="${install_root}/bin/cargo-proof"
if [[ -x "${cargo_bin}.exe" ]]; then
  cargo_bin="${cargo_bin}.exe"
fi
[[ -x "${cargo_bin}" || -f "${cargo_bin}" ]] || fail "missing installed binary"

ROOT_NATIVE="$(to_cargo_path "${ROOT}")"
INSTALL_NATIVE="$(to_cargo_path "${install_root}")"
python3 - "${cargo_bin}" "${ROOT_NATIVE}" "${INSTALL_NATIVE}" "${workspace_debug_bin}" "${workspace_debug_bin_exe}" <<'PY'
import sys
from pathlib import Path

bin_path = Path(sys.argv[1]).resolve()
root = Path(sys.argv[2]).resolve()
install_root = Path(sys.argv[3]).resolve()
ws_debug = Path(sys.argv[4]).resolve()
ws_debug_exe = Path(sys.argv[5]).resolve()
try:
    bin_path.relative_to(install_root)
except ValueError as err:
    raise SystemExit(f"installed binary not under install root: {bin_path}") from err
crates_dir = root / "crates"
if crates_dir in bin_path.parents:
    raise SystemExit(f"WorkspacePathLeak: binary under workspace crates/: {bin_path}")
target_debug = root / "target" / "debug"
if target_debug in bin_path.parents:
    raise SystemExit(f"WorkspaceTargetLeak: binary under workspace target/debug: {bin_path}")
for candidate in (ws_debug, ws_debug_exe):
    if candidate.exists() and candidate.resolve() == bin_path:
        raise SystemExit(f"WorkspaceTargetLeak: decisive binary equals workspace debug build {bin_path}")
print("binary_isolation_ok")
PY

version_output="$("${cargo_bin}" --version | tr -d '\r')"
printf '%s\n' "${version_output}"
printf '%s\n' "${version_output}" | grep -F "cargo-proof ${proof_version}" >/dev/null \
  || fail "installed version mismatch: ${version_output}"

log "cargo-proof --help"
"${cargo_bin}" --help >/dev/null

log "cargo-proof identity"
"${cargo_bin}" identity >/dev/null

declare -a install_closure=(
  effortless-repo-protocol
  proof-protocol
  proof-engine
  cargo-proof
)

log "confirming internal deps resolve from extracted/patched graph (not workspace crates/)"
resolve_meta_path="${offline_root}/resolve-metadata.json"
cargo metadata --format-version 1 --manifest-path "${extracted_bin_pkg}/Cargo.toml" \
  >"${resolve_meta_path}"
python3 - "${resolve_meta_path}" "${ROOT_NATIVE}" "${EXTRACTED_NATIVE}" "${install_closure[@]}" <<'PY'
import json, sys
from pathlib import Path

meta = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
root = Path(sys.argv[2]).resolve()
extracted = Path(sys.argv[3]).resolve()
internal = set(sys.argv[4:])
seen = set()
for pkg in meta.get("packages", []):
    name = pkg.get("name")
    if name not in internal:
        continue
    seen.add(name)
    manifest = Path(pkg["manifest_path"]).resolve()
    crates_dir = root / "crates"
    if crates_dir in manifest.parents or str(manifest).startswith(str(crates_dir)):
        raise SystemExit(f"WorkspacePathLeak: {name} manifest={manifest}")
    if name == "cargo-proof":
        try:
            manifest.relative_to(extracted)
        except ValueError as err:
            raise SystemExit(f"cargo-proof not under extracted tree: {manifest}") from err
missing = internal - seen
if missing:
    raise SystemExit(f"PackageMissing from metadata: {sorted(missing)}")
print("isolation_ok")
PY

os_name="$(uname -s | tr '[:upper:]' '[:lower:]')"
case "${os_name}" in
  mingw*|msys*|cygwin*) os_name="windows" ;;
  darwin*) os_name="macos" ;;
  linux*) os_name="linux" ;;
esac
arch_name="$(uname -m)"
case "${arch_name}" in
  x86_64|amd64) arch_name="x86_64" ;;
  aarch64|arm64) arch_name="aarch64" ;;
esac

rustc_version="$(rustc --version 2>/dev/null | tr -d '\r' || true)"
cargo_version="$(cargo --version 2>/dev/null | tr -d '\r' || true)"

log "writing receipt ${receipt}"
CRATE_RECORDS="$(printf '%s\n' "${crate_records[@]}")" \
RECEIPT_PATH="${receipt}" \
SCHEMA_ID="${schema_id}" \
CRATE_SET_SCHEMA_ID="${crate_set_schema_id}" \
WORKSPACE_VERSION="${version}" \
GIT_HEAD="${git_head}" \
OS_NAME="${os_name}" \
ARCH_NAME="${arch_name}" \
RUSTC_VERSION="${rustc_version}" \
CARGO_VERSION="${cargo_version}" \
VERSION_OUTPUT="${version_output}" \
INSTALL_CODE="${install_code}" \
CRATE_ORDER="$(printf '%s\n' "${crates[@]}")" \
python3 <<'PY'
import json
import os

records = []
for line in os.environ["CRATE_RECORDS"].splitlines():
    if not line.strip():
        continue
    name, version, crate_file, sha256, size, extracted = line.split("|", 5)
    records.append(
        {
            "name": name,
            "version": version,
            "crate_file": crate_file,
            "sha256": sha256,
            "size_bytes": int(size),
            "extracted_dir": extracted,
            "no_path_deps": True,
        }
    )

order = [line for line in os.environ["CRATE_ORDER"].splitlines() if line.strip()]

receipt = {
    "schema_version": 1,
    "schema_id": os.environ["SCHEMA_ID"],
    "tool": "cargo-proof",
    "result": "Passed",
    "claim_boundary": [
        "six_crate_proof_package_graph",
        "extracted_path_install_outside_workspace",
        "source_checkout_denied_during_decisive_install",
        "no_proof_or_test_invocation",
        "no_workspace_target_debug_binary",
    ],
    "candidate": {
        "workspace_version": os.environ["WORKSPACE_VERSION"],
        "crate_set_schema_id": os.environ["CRATE_SET_SCHEMA_ID"],
        "git_head": os.environ["GIT_HEAD"] or None,
    },
    "environment": {
        "os": os.environ["OS_NAME"],
        "arch": os.environ["ARCH_NAME"],
        "rustc_version": os.environ["RUSTC_VERSION"] or None,
        "cargo_version": os.environ["CARGO_VERSION"] or None,
        "network_posture": "may_use_crates_io_for_external_deps",
        "isolation_mechanism": "path_patch_extracted",
    },
    "package_set": {"order": order, "crates": records},
    "isolation": {
        "fresh_cargo_home": True,
        "install_from_extracted_package": True,
        "workspace_paths_absent": True,
        "source_checkout_denied": True,
        "workspace_target_debug_rejected": True,
    },
    "install": {
        "method": "cargo_install_path_extracted_with_patch",
        "version_output": os.environ["VERSION_OUTPUT"],
        "exit_code": int(os.environ["INSTALL_CODE"]),
    },
    "limitations": [
        "path_patch_not_classic_local_registry",
        "linux_hosted_claim_primary",
    ],
}

with open(os.environ["RECEIPT_PATH"], "w", encoding="utf-8") as handle:
    json.dump(receipt, handle, indent=2)
    handle.write("\n")
PY

durable_bin="${work_dir}/install/bin/cargo-proof"
if [[ -f "${cargo_bin}.exe" || "${cargo_bin}" == *.exe ]]; then
  durable_bin="${durable_bin}.exe"
fi
mkdir -p "$(dirname "${durable_bin}")"
cp "${cargo_bin}" "${durable_bin}"
log "durable install copy: ${durable_bin}"

log "ProofCandidateInstallSmokeV1 Passed for workspace ${version}"
log "receipt: ${receipt}"
